name = "vr-q-c-hk-scan-api"
main = "src/index.ts"
compatibility_date = "2026-07-04"

[vars]
PUBLIC_SITE_URL = "https://vr.q-c.hk"
STORAGE_PROVIDER = "local"
MAX_USDZ_MB = "500"
MAX_IMAGES_ZIP_MB = "1024"

[[d1_databases]]
binding = "DB"
database_name = "vrqc-scans"
database_id = "4920ac15-b948-4664-87e2-2975a54fed51"
